# Generated by Django 5.2.3 on 2025-07-08 20:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicpage',
            name='tiles',
            field=wagtail.fields.StreamField([('tile_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Images', 'max_num': 10}), 2: ('wagtail.blocks.StructBlock', [[('images', 1)]], {'label': 'Mosaic Tile'})}, help_text='Use this section to create a mosaic layout with images.'),
        ),
    ]
