# Generated by Django 5.2.3 on 2025-07-12 11:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0003_alter_mosaicpage_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicpage',
            name='tiles',
            field=wagtail.fields.StreamField([('tile_block', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Images', 'max_num': 10}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fade', 'Fade'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('flip-x', 'Flip X'), ('flip-y', 'Flip Y')], 'label': 'Transition Effect'}), 3: ('wagtail.blocks.StructBlock', [[('images', 1), ('transition', 2)]], {'label': 'Mosaic Tile'})}, help_text='Use this section to create a mosaic layout with images.'),
        ),
    ]
