# Generated by Django 5.2.3 on 2025-07-12 11:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0004_alter_mosaicpage_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicpage',
            name='tiles',
            field=wagtail.fields.StreamField([('tile_block', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Images', 'max_num': 10}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link when tile is clicked', 'label': 'Link URL', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title text', 'label': 'Title', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'label': 'Description', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If checked, title and description will only appear on hover. If unchecked, they will always be visible when present.', 'label': 'Show text only on hover', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fade', 'Fade'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('flip-x', 'Flip X'), ('flip-y', 'Flip Y')], 'label': 'Transition Effect'}), 7: ('wagtail.blocks.StructBlock', [[('images', 1), ('link', 2), ('title', 3), ('description', 4), ('text_on_hover', 5), ('transition', 6)]], {'label': 'Mosaic Tile'})}, help_text='Use this section to create a mosaic layout with images.'),
        ),
    ]
