# Generated by Django 5.2.3 on 2025-07-12 12:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0005_alter_mosaicpage_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicpage',
            name='tiles',
            field=wagtail.fields.StreamField([('tile_block', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title text', 'label': 'Title', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'label': 'Description', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If checked, title and description will only appear on hover. If unchecked, they will always be visible when present.', 'label': 'Show text only on hover', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link when tile is clicked', 'label': 'Link URL', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fade', 'Fade'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('flip-x', 'Flip X'), ('flip-y', 'Flip Y')], 'label': 'Transition Effect'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2s', '2 seconds'), ('3s', '3 seconds'), ('4s', '4 seconds'), ('5s', '5 seconds'), ('7s', '7 seconds'), ('10s', '10 seconds'), ('15s', '15 seconds'), ('20s', '20 seconds'), ('30s', '30 seconds'), ('1m', '1 minute'), ('random:3-7', 'Random (3-7s)'), ('random:4-10', 'Random (4-10s)'), ('random:5-15', 'Random (5-15s)'), ('random:10-20', 'Random (10-20s)'), ('random:15-30', 'Random (15-30s)'), ('random:30-60', 'Random (30-60s)')], 'help_text': 'How often the images change', 'label': 'Image Change Interval'}), 6: ('wagtail.images.blocks.ImageBlock', [], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Images', 'max_num': 10}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('text_on_hover', 2), ('link', 3), ('transition', 4), ('image_change_interval', 5), ('images', 7)]], {'label': 'Mosaic Tile'})}, help_text='Use this section to create a mosaic layout with images.'),
        ),
    ]
