# Generated by Django 5.2.3 on 2025-07-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0006_alter_mosaicpage_tiles'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaicpage',
            name='content_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='mosaicpage',
            name='layout',
            field=models.CharField(choices=[('content-left', 'Content Left'), ('content-right', 'Content Right')], default='content-left', help_text='Choose the layout for the mosaic page.', max_length=13),
        ),
    ]
